<!---
XML IS CASESENSITIVE - SO USE LOWER CASE LETTERS
-->

<!-- xml 1.0 -->

- Must input elements be inside forms?
    No
- Find and name the EMPTY elements.

- May a table be empty? May a tr?

- What are the possible attributes of a h2?
    Inline

<!-- xml 1.1-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookscanon [
<!ELEMENT bookscanon (books+)>
<!ELEMENT book (title, edition, authors, publisher, pages, isbn, price, currency, comments)>
          <!ATTLIST book
                     ref ID #REQUIRED
                     mycanon (mdu|all) #REQUIRED>
          <!ELEMENT title (#PCDATA)>
          <!ELEMENT edition (#PCDATA)>
          <!ELEMENT authors (author+)>
          <!ELEMENT author (firstname, lastname)>
                    <!ELEMENT firstname (#PCDATA)>
                    <!ELEMENT lastname (#PCDATA)>
          <!ELEMENT publisher (name, year, place)>
                    <!ELEMENT name (#PCDATA)>
                    <!ELEMENT year (#PCDATA)>
                    <!ELEMENT place (#PCDATA)>
          <!ELEMENT pages (#PCDATA)>
          <!ELEMENT isbn (#PCDATA)>
          <!ELEMENT price (#PCDATA)>
          <!ELEMENT currency (#PCDATA)>
          <!ELEMENT comments (comments+)>
                    <!ELEMENT comment (#PCDATA)>
]>

<bookscanon>
  <book ref="Llo08" mycanon="mdu,all">
    <title>Learn How to Build Web Sites the Right Way from Scratch</title>
    <edition>2</edition>
    <authors>
      <author>
        <firstname>Ian</firstname>
        <lastname>Lloyd</lastname>
      </author>
    </authors>
    <publisher>
      <name>SitePoint</name>
      <year>2008</year>
      <place>Collingwood, VIC, Australia</place>
    </publisher>
    <pages>300</pages>
    <isbn></isbn>
    <price>9.73</price>
    <currency>EU&#8364;</currency>
    <comments>
      <comment>1. sem: Chapters 1-7</comment>
    </comments>
  </book>

  <book ref="Shu08" mycanon="mdu">
    <title>Learning ActionScript 3.0</title>
    <edition>2</edition>
    <authors>
      <author>
        <firstname>Rich</firstname>
        <lastname>Shupe</lastname>
      </author>
      <author>
        <firstname>Zevan</firstname>
        <lastname>Rosser</lastname>
      </author>
    </authors>
    <publisher>
      <name>O'Reilly</name>
      <year>2008</year>
      <place>Sebastopol, CA, USA</place>
    </publisher>
    <pages>384</pages>
    <isbn>978-0596527877</isbn>
    <price>8.73</price>
    <currency>US$</currency>
    <comments>
      <comment>1. sem: Chapters 1-7</comment>
    </comments>
  </book>

  <book ref="Nix09" mycanon="mdu">
    <title>Learning PHP, MySQL, and JavaScript</title>
    <edition>2</edition>
    <authors>
      <author>
        <firstname>Robin</firstname>
        <lastname>Nixon</lastname>
      </author>
    </authors>
    <publisher>
      <name>O'Reilly</name>
      <year>2009</year>
      <place>Sebastopol, CA, USA</place>
    </publisher>
    <pages>120</pages>
    <isbn></isbn>
    <price></price>
    <currency></currency>
    <comments>
      <comment>2. sem: Chapters 1-7, 11, 14-17</comment>
      <comment>3. sem: Chapters 8-10</comment>
    </comments>
  </book>

  <book ref="For04" mycanon="mdu,all">
    <title>SQL in 10 Minutes</title>
    <edition>3</edition>
    <authors>
      <author>
        <firstname>Ben</firstname>
        <lastname>Forta</lastname>
      </author>
    </authors>
    <publisher>
      <name>Sams Publishing</name>
      <year>2004</year>
      <place>Indianapolis, IN, USA</place>
    </publisher>
    <pages></pages>
    <isbn></isbn>
    <price>120</price>
    <currency></currency>
    <comments>
      <comment>3. sem: Chapters 1-17</comment>
    </comments>
  </book>

</bookscanon>
